ExProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace='users')),
]

main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    
    path('create/project/', views.CreateProject.as_view(), name='create_project'),
    path('create/task/<int:pk>/', views.CreateTask.as_view(), name='create_task'),
    
    path('delete/project/<int:pk>/', views.DeleteProject.as_view(), name='delete_project'),
    path('delete/task/<int:pk>/', views.DeleteTask.as_view(), name='delete_task'),
    
    path('change/project/<int:pk>/', views.ChangeProject.as_view(), name='change_project'),
    path('change/task/<int:pk>/', views.ChangeTask.as_view(), name='change_task'),
    
    path('project/<int:pk>/', views.ProjectView.as_view(), name='project'),
    path('task/<int:pk>/', views.TaskView.as_view(), name='task'),
    
    path('join_project/<int:pk>/', views.JoinProject.as_view(), name='join_project'),
    path('cancel_project/<int:pk>/', views.CancelProject.as_view(), name='cancel_project'),
    path('accept_project/<int:pk>/<int:upk>/', views.AcceptProject.as_view(), name='accept_project'),
    path('decline_project/<int:pk>/<int:upk>/', views.DeclineProject.as_view(), name='decline_project'),
    path('quit_project/<int:pk>/<int:upk>/', views.QuitProject.as_view(), name='quit_project'),
    path('mod_project/<int:pk>/<int:upk>/', views.ModerationProject.as_view(), name='mod_project'),
    path('take_task/<int:pk>/', views.TakeTask.as_view(), name='take_task'),
    path('complete_task/<int:pk>/', views.CompleteTask.as_view(), name='complete_task'),
    
    path('project_requests/<int:pk>/', views.RequestsView.as_view(), name='project_requests'),
    path('project_members/<int:pk>/', views.MembersView.as_view(), name='project_members'),
    
    path('project_finish/<int:pk>/', views.ProjectFinish.as_view(), name='project_finish'),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

main/models.py
from django.db import models


class Project(models.Model):
    class Status(models.TextChoices):
        ACTIVE = 'active', 'Активен'
        COMPLETED = 'completed', 'Завершен'
        PAUSED = 'paused', 'Приостановлен'
        
    title = models.CharField(max_length=50, verbose_name='Название')
    description = models.CharField(max_length=200, verbose_name='Описание')
    start_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    end_date = models.DateTimeField(default=None, null=True, verbose_name='Дата окончания')
    status = models.TextField(choices=Status.choices, default=Status.ACTIVE, verbose_name='Статус')
    
    creator = models.ForeignKey('users.User', on_delete=models.SET_NULL, null=True, verbose_name='Создатель', related_name='project')
    moders = models.ManyToManyField('users.User', verbose_name='Важные Шишки', related_name='mods')
    members = models.ManyToManyField('users.User', verbose_name='Участники', related_name='mems')
    requests = models.ManyToManyField('users.User', verbose_name='Запросы', related_name='reqs')
    
    class Meta:
        ordering = ['-pk']

class Task(models.Model):
    class Status(models.TextChoices):
        PROGRESS = 'progress', 'Активна'
        COMPLETED = 'completed', 'Завершена'
        NOTSTARTED = 'not_started', 'Не_начата'
    
    class Priority(models.TextChoices):
        HIGH = 'high', 'Высокий'
        MEDIUM = 'medium', 'Средний'
        LOW = 'low', 'Низкий'
        
        
    title = models.CharField(max_length=50, verbose_name='Название')
    description = models.CharField(max_length=200, verbose_name='Описание')
    project = models.ForeignKey('main.Project', on_delete=models.CASCADE, verbose_name='Проект', related_name='tasks')
    priority = models.TextField(choices=Priority.choices, verbose_name='Приоритет')
    start_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    end_date = models.DateTimeField(default=None, null=True, verbose_name='Дата окончания')
    status = models.TextField(choices=Status.choices, default=Status.NOTSTARTED, verbose_name='Статус')
    
    taked = models.ForeignKey('users.User', on_delete=models.SET_NULL, null=True, verbose_name='Кем Взято', related_name='tasks')
    
    class Meta:
        ordering = ['priority', '-pk']
    
    @classmethod
    def get_ordered_queyset(cls):
        return cls.objects.annotate(
            order_priority=models.Case(
                models.When(status=cls.Status.COMPLETED, then=4),
                models.When(priority=cls.Priority.HIGH, then=1),
                models.When(priority=cls.Priority.MEDIUM, then=2),
                models.When(priority=cls.Priority.LOW, then=3),
                output_field=models.IntegerField(),
            )
        ).order_by('order_priority')

class Comment(models.Model):
    user = models.ForeignKey('users.User', on_delete=models.SET_NULL, null=True, verbose_name='Пользователь', related_name='comms')
    text = models.CharField(max_length=100, verbose_name='Текст')
    task = models.ForeignKey('main.Task', on_delete=models.CASCADE, verbose_name='Задача', related_name='comms')
    
    class Meta:
        ordering = ['-pk']

main/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Project, Task, Comment


class CreateProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description']
        
class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'priority']
        
class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

main/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, UpdateView, ListView
from itertools import chain
from django.utils.timezone import now as tnow
from .forms import CreateProjectForm, CreateTaskForm, CreateCommentForm
from .models import Project, Task, Comment
from .utils import LoginMixn

def to_super(u):
    return not u.is_superuser
def to_creator(u, p):
    return not p.creator == u and to_super(u)
def to_moder(u, p):
    return not u in p.moders.all() and to_creator(u, p)
def to_member(u, p):
    return not u in p.members.all() and to_moder(u, p)

class Home(LoginMixn, TemplateView):
    template_name = 'main/home.html'
    extra_context = {'title': 'Home', 'projects': Project.objects}
    
class CreateProject(LoginMixn, CreateView):
    template_name = 'main/create_project.html'
    form_class = CreateProjectForm
    extra_context = {'title': 'Create Project'}
    
    def get_success_url(self):
        return reverse_lazy('project', kwargs={'pk': self.object.pk})
    
    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)

class CreateTask(LoginMixn, CreateView):
    template_name = 'main/create_task.html'
    form_class = CreateTaskForm
    extra_context = {'title': 'Create Task'}
    
    def get_success_url(self):
        return reverse_lazy('task', kwargs={'pk': self.object.pk})
    
    def form_valid(self, form):
        form.instance.project = Project.objects.get(pk = self.kwargs['pk'])
        return super().form_valid(form)
    
    def get(self, request, *args, **kwargs):
        p = Project.objects.get(pk = self.kwargs['pk'])
        if to_moder(self.request.user, p):
            return HttpResponseRedirect(reverse_lazy('home'))
        else:
            return super().get(request, *args, **kwargs)
    
class ProjectView(LoginMixn, TemplateView):
    template_name = 'main/project.html'
    pk_url_kwarg = 'pk'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = Project.objects.get(pk=self.kwargs[self.pk_url_kwarg])
        context['tasks'] = Task.get_ordered_queyset().filter(project=context['project'])
        context['title'] = context['project'].title
        return context

class TaskView(LoginMixn, CreateView):
    template_name = 'main/task.html'
    pk_url_kwarg = 'pk'
    form_class = CreateCommentForm
    
    def get_success_url(self):
        return reverse_lazy('task', kwargs={'pk': self.kwargs[self.pk_url_kwarg]})
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.task = Task.objects.get(pk = self.kwargs[self.pk_url_kwarg])
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = self.t
        context['comms'] = Comment.objects.filter(task=self.t)
        context['title'] = context['task'].title
        return context
    
    def get(self, request, *args, **kwargs):
        self.t = Task.objects.get(pk = self.kwargs[self.pk_url_kwarg])
        if to_member(self.request.user, self.t.project):
            return HttpResponseRedirect(reverse_lazy('home'))

        return super().get(request, *args, **kwargs)
    
class DeleteProject(LoginMixn, View):
    pk_url_kwarg = 'pk'
    def get(self, request, *args, **kwargs):
        p = Project.objects.get(pk=self.kwargs[self.pk_url_kwarg])
        if to_creator(self.request.user, p): 
            return HttpResponseRedirect(reverse_lazy('project', kwargs={'pk': self.kwargs[self.pk_url_kwarg]}))
        p.delete()
        return HttpResponseRedirect(reverse_lazy('home'))

class DeleteTask(LoginMixn, View):
    pk_url_kwarg = 'pk'
    def get(self, request, *args, **kwargs):
        t = Task.objects.get(pk=self.kwargs[self.pk_url_kwarg])
        if to_moder(self.request.user, t.project):
            return HttpResponseRedirect(reverse_lazy('task', kwargs={'pk': self.kwargs[self.pk_url_kwarg]}))
        t.delete()
        return HttpResponseRedirect(reverse_lazy('task', kwargs={'pk': self.kwargs[self.pk_url_kwarg]}))

class ChangeProject(LoginMixn, UpdateView):
    model = Project
    form_class = CreateProjectForm
    template_name = 'main/change_project.html'
    extra_context = {'title': 'Change Project'}
    
    def get_success_url(self):
        return reverse_lazy('project', kwargs={'pk': self.object.pk})
    
    def get(self, request, *args, **kwargs):
        t = Task.objects.get(pk=kwargs[self.pk_url_kwarg])
        if to_moder(self.request.user, t.project):
            return HttpResponseRedirect('home')
        return super().get(request, *args, **kwargs)
    
class ChangeTask(LoginMixn, UpdateView):
    model = Task
    form_class = CreateTaskForm
    template_name = 'main/change_task.html'
    extra_context = {'title': 'Change Task'}
    pk_url_kwarg = 'pk'
    
    def get_success_url(self):
        return reverse_lazy('task', kwargs={'pk': self.object.pk})
    
    def get(self, request, *args, **kwargs):
        t = Task.objects.get(pk=kwargs[self.pk_url_kwarg])
        if to_moder(self.request.user, t.project):
            return HttpResponseRedirect('home')
        return super().get(request, *args, **kwargs)
    
class JoinProject(LoginMixn, View):
    pk_url_kwarg = 'pk'
    def get(self, request, *args, **kwargs):
        p = Project.objects.get(pk=self.kwargs[self.pk_url_kwarg])
        p.requests.add(self.request.user)
        return HttpResponseRedirect(reverse_lazy('project', kwargs={'pk': self.kwargs[self.pk_url_kwarg]}))

class AcceptProject(LoginMixn, View):
    pk_url_kwarg = 'pk'
    def get(self, request, *args, **kwargs):
        p = Project.objects.get(pk=self.kwargs[self.pk_url_kwarg])
        u = get_user_model().objects.get(pk=self.kwargs['upk'])
        if to_creator(self.request.user, p):
            return HttpResponseRedirect(reverse_lazy('home'))
        p.requests.remove(u)
        p.members.add(u)
        return HttpResponseRedirect(reverse_lazy('project_requests', kwargs={'pk': self.kwargs[self.pk_url_kwarg]}))
    
class DeclineProject(LoginMixn, View):
    pk_url_kwarg = 'pk'
    def get(self, request, *args, **kwargs):
        p = Project.objects.get(pk=self.kwargs[self.pk_url_kwarg])
        u = get_user_model().objects.get(pk=self.kwargs['upk'])
        if to_creator(self.request.user, p):
            return HttpResponseRedirect(reverse_lazy('home'))
        p.requests.remove(u)
        return HttpResponseRedirect(reverse_lazy('project_requests', kwargs={'pk': self.kwargs[self.pk_url_kwarg]}))

class QuitProject(LoginMixn, View):
    pk_url_kwarg = 'pk'
    def get(self, request, *args, **kwargs):
        p = Project.objects.get(pk=self.kwargs[self.pk_url_kwarg])
        u = get_user_model().objects.get(pk=self.kwargs['upk'])
        p.members.remove(u)
        p.moders.remove(u)
        Task.objects.filter(taked=u).update(taked=None, status=Task.Status.NOTSTARTED)
        return HttpResponseRedirect(reverse_lazy('project', kwargs={'pk': self.kwargs[self.pk_url_kwarg]}))
    
class CancelProject(LoginMixn, View):
    pk_url_kwarg = 'pk'
    def get(self, request, *args, **kwargs):
        p = Project.objects.get(pk=self.kwargs[self.pk_url_kwarg])
        p.requests.remove(self.request.user)
        return HttpResponseRedirect(reverse_lazy('project', kwargs={'pk': self.kwargs[self.pk_url_kwarg]}))

class ModerationProject(LoginMixn, View):
    pk_url_kwarg = 'pk'
    def get(self, request, *args, **kwargs):
        p = Project.objects.get(pk=self.kwargs[self.pk_url_kwarg])
        u = get_user_model().objects.get(pk=self.kwargs['upk'])
        if to_creator(self.request.user, p):
            return HttpResponseRedirect(reverse_lazy('home'))
        if u in p.moders.all():
            p.members.add(u)
            p.moders.remove(u)
        else:
            p.members.remove(u)
            p.moders.add(u)
            
        return HttpResponseRedirect(reverse_lazy('project_members', kwargs={'pk': self.kwargs[self.pk_url_kwarg]}))

class TakeTask(LoginMixn, View):
    pk_url_kwarg = 'pk'
    def get(self, request, *args, **kwargs):
        t = Task.objects.get(pk=self.kwargs[self.pk_url_kwarg])
        if t.status == Task.Status.NOTSTARTED:
            t.status = Task.Status.PROGRESS
            t.taked = self.request.user
        else:
            t.status = Task.Status.NOTSTARTED
            t.taked = None
        t.save()
        return HttpResponseRedirect(reverse_lazy('task', kwargs={'pk': self.kwargs[self.pk_url_kwarg]}))

class CompleteTask(LoginMixn, View):
    pk_url_kwarg = 'pk'
    def get(self, request, *args, **kwargs):
        t = Task.objects.get(pk=self.kwargs[self.pk_url_kwarg])
        t.status = Task.Status.COMPLETED
        t.end_date = tnow()
        t.save()
        return HttpResponseRedirect(reverse_lazy('task', kwargs={'pk': self.kwargs[self.pk_url_kwarg]}))

class MembersView(LoginMixn, ListView):
    template_name = 'main/project_members.html'
    context_object_name = 'reqs'
    extra_context = {'title': 'Members'}
    pk_url_kwarg = 'pk'
    
    def get_queryset(self):
        p = Project.objects.get(pk=self.kwargs[self.pk_url_kwarg])
        return list(chain(p.members.all(), p.moders.all()))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pid'] = self.kwargs[self.pk_url_kwarg]
        context['proj'] = Project.objects.get(pk=self.kwargs[self.pk_url_kwarg])
        return context
    
class RequestsView(MembersView):
    template_name = 'main/project_requests.html'
    extra_context = {'title': 'Requests'}

    def get_queryset(self):

main/templates/main/change_project.html
{% extends "base.html" %}

{% block content %}
<form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Change</button>
</form>
{% endblock content %}

main/templates/main/change_task.html
{% extends "base.html" %}

{% block content %}
<form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Change</button>
</form>
{% endblock content %}

main/templates/main/create_project.html
{% extends "base.html" %}

{% block content %}
<form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Create</button>
</form>
{% endblock content %}

main/templates/main/create_task.html
{% extends "base.html" %}

{% block content %}
<form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Create</button>
</form>
{% endblock content %}

main/templates/main/home.html
{% extends "base.html" %}

{% block content %}
<div>
    <span>{{ user.username }}</span> | 
    <a href="{% url "users:logout" %}">Logout</a>
</div>
<div>
    <div>
        <a href="{% url "create_project" %}">Create project</a>
    </div>
    <div>
        <form id='search_project'>
            <span>Find Project</span>
            <input id='search_project_input' type="text" placeholder='Enter project id' required>
            <button>Enter</button>
        </form>
    </div>
    <div>
        <span>My Projects:</span>
        <div>
            {% for project in projects.all %}
            {% if project.creator == user %}
            {% include "main/includes/project.html" %}
            {% endif %}
            {% endfor %}
        </div>
    </div>
    <div>
        <span>Current Projects: </span>
        <div>
            {% for project in projects.all %}
            {% if user in project.members.all or project.moders.all %}
                {% if project.creator != user %}
                {% include "main/includes/project.html" %}
                {% endif %}
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    document.getElementById('search_project').addEventListener('submit', function(event) {
        event.preventDefault()
        const searchValue = document.getElementById('search_project_input').value
        const url = "{% url "project" '0' %}".replace('0', searchValue)
        window.location.href = url
    });
</script>
{% endblock scripts %}

main/templates/main/project.html
{% extends "base.html" %}

{% block content %}
<h3>{{ project.description }}</h3>

{% if user != project.creator %}
    {% if user in project.members.all or user in project.moders.all %}
    <div><a href="{% url "quit_project" project.pk user.pk %}">Покинуть проект</a></div>
    {% elif user in project.requests.all %}
    <div><a href="{% url "cancel_project" project.pk %}">Отменить заявку</a></div>
    {% else %}
    <div><a href="{% url "join_project" project.pk %}">Вступить в проект</a></div>
    {% endif %}
{% endif %}

{% if user == project.creator or user.is_superuser %}
<div><a href="{% url "delete_project" project.pk %}">Удалить Проект</a></div>
<div><a href="{% url "project_requests" project.pk %}">Запросы на вступление</a></div>
<div><a href="{% url "project_finish" project.pk %}">Закончить проект</a></div>
{% endif %}

{% if user not in project.members.all %}
<div><a href="{% url "change_project" project.pk %}">Изменить проект</a></div>
<div><a href="{% url "create_task" project.pk %}">Создать задачу</a></div>
{% endif %}
<div><a href="{% url "project_members" project.pk %}">Участники</a></div>

<div>
    <span>Задачи: </span>
    <div>
        {% for task in tasks %}
        {% include "main/includes/task.html" %}
        {% endfor %}
    </div>
</div>
{% endblock content %}

main/templates/main/project_members.html
{% extends "base.html" %}

{% block content %}

{% for req in reqs %}
    {% include "main/includes/member.html" %}
{% endfor %}

{% endblock content %}

main/templates/main/project_requests.html
{% extends "base.html" %}

{% block content %}
{% for req in reqs %}
{% include "main/includes/request.html" %}
{% endfor %}
{% endblock content %}

main/templates/main/task.html
{% extends "base.html" %}

{% block content %}
<h3>{{ task.description }}</h3>

{% if user not in task.project.members.all %}
<div><a href="{% url "delete_task" task.pk %}">Удалить</a></div>
<div><a href="{% url "change_task" task.pk %}">Изменить</a></div>
{% endif %}

{{task.status}}: 

{% if task.status == 'completed' %}
    Done | {{task.end_date}}
{% elif not task.taked %}
    <a href="{% url "take_task" task.pk %}">Take Task</a>
{% elif task.taked and task.taked == user %}
    <a href="{% url "take_task" task.pk %}">Cancel Task</a>
    <div>
        <span>Comleted? &gt; </span>
        <a href="{% url "complete_task" task.pk %}">Finish Task</a>
    </div>
{% else %}
    {{task.taked}}
{% endif %}

<div>
    <div>
        <form method='POST'>
            {% csrf_token %}
            <span>Comments:</span>
            {{form.as_p}}
            <button type='submit'>Send</button>
        </form>
    </div>
    <div>
        {% for comm in comms %}
        <div>{{comm.user}}: {{comm.text}}</div>
        {% endfor %}
    </div>
</div>

{% endblock content %}